AWSTemplateFormatVersion: 2010-09-09
Description: WebApp Template using ECS, Autoscaling, and CloudWatch
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Parent Stack
        Parameters:
          - ParentVPCStack
Parameters:
  ParentVPCStack:
    Description: Stack name of the VPC Template
    Type: String
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Key for ssh access
    Default: dev
  DesiredCapacity:
    Type: Number
    Default: '2'
    Description: Number of instances
  MaxSize:
    Type: Number
    Default: '4'
    Description: Max number of instances
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
  ImageID:
    Description: Latest ECS optimised amazon Linux 2 Image eu-west-2
    Type: AWS::EC2::Image::Id
    Default: ami-0229ad66a59113c47
Resources: 
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: WebAppCluster
      Tags:
        - Key: Name
          Value: WebAppCluster
        - Key: Environment
          Value: Development
  SGALB:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for the Application Load Balancer
      VpcId: !ImportValue
        Fn::Sub: ${ParentVPCStack}-VPC
  SGWebAPP:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for the Web Application
      VpcId: !ImportValue
        Fn::Sub: ${ParentVPCStack}-VPC
  SGALBHTTPinbound:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref 'SGALB'
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      CidrIp: '0.0.0.0/0'
      Description: HTTP Internet
  SGSGWebfromALB:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref 'SGWebAPP'
      IpProtocol: tcp
      FromPort: 80
      ToPort: 80
      SourceSecurityGroupId: !Ref 'SGALB'
      Description: HTTP ALB
  ECSCWLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join
        - '-'
        - - ECSCWLogGroup
          - !Ref 'AWS::StackName'
      RetentionInDays: 14
Outputs: